server:
  port: 9000
  error:
    whitelabel:
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/AnimeDB
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        show-sql: true
        format-sql: true
  servlet:
    multipart:
      max-file-size: 10MB # 한 파일당 최대 용량 제한
      max-request-size: 50MB # 모든 파일의 최대 용량 제한
  data:
    web:
      pageable:
        default-page-size: 10 # 한 페이지당 게시글 수
        one-indexed-parameters: true # 페이지를 0부터 말고 1부터
        
  # security:
  #   oauth2:
  #     client:
  #       registration:
  #         google:
  #           client-id: NEVER REVEAL THIS SENSITIVE PART ON THIS FILE!
  #           client-secret: NEVER REVEAL THIS SENSITIVE PART ON THIS FILE!
  #           scope: profile, email
  #       provider:
  #         google:
  #           authorization-uri: https://accounts.google.com/o/oauth2/auth
  #           token-uri: https://oauth2.googleapis.com/token
  #           user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  #           user-name-attribute: sub

springdoc:
  api-docs:
    path: /api-docs
    # enabled: false
  swagger-ui:
    path: /swagger-ui.html
    # enabled: false

file:
  upload-dir: uploads/profile-images/

